### ISSUE TITLE
Not working as advertised

### ISSUE THREAD

**Issue by Daeymon** [Fisch03/SDH-QuickLaunch#12]
When selecting a Flatpak and selecting "Launch", it creates a non-steam game and launches it. I would figure using this button should launch the app without leaving an entry in the library that I have to manually remove. This happens with all the Flatpaks I have installed.

But also when selecting a Flatpak and selecting "Create shortcut", nothing happens.

SteamOS 3.5.7
Decky Loader 2.11.1
Quick Launch 1.0.2-1

**Comment by Fisch03** [comment]
This might be the intended behaviour. To launch any game on the steam deck (in Gaming mode), it needs a shortcut. What this plugin does is create a single shortcut for itself, that gets automatically edited to launch whatever program you choose. So that there is one shortcut is normal. Feel free to hide it if it annoys you, it wont affect functionality :)

That being said the "Create Shortcut" button not working is not normal. Have you verified that this still occurs after a reboot? Sometimes SteamOS gets a bit wonky with shortcuts

**Comment by Daeymon** [comment]
Okay, I didn't realise it would reuse the same shortcut which I could hide, which I have now done, and it now does work as advertised. So that is good. Maybe have that added to the Readme to clarify that.

Based on what you have now told me, I would assume the reason the "Create Shortcut" button didn't work is because the shortcut already existed from pressing the "Launch" button. I assumed it would make a fresh shortcut each time. A reboot didn't change its behaviour.

**Comment by Fisch03** [comment]
The "Create Shortcut" button is specifically for the case where you want to create a new Shortcut for some application and it should create a completely new Shortcut everytime you press it. Think of it as a shorthand for adding a new non-steam game to your library without having to go to desktop mode. 
It seems you're mainly planning using this plugin for the launching functionality, but if that is something you're interested in as well and want me to look into why its not working for you right now do let me know!
